apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: itiselector
spec:
  replicas: 2
  selector:
    matchLabels:
      type: itiselector
  template:
    metadata:
      name: myapp
      labels:
        type: itiselector
    spec:
      containers:
        - name: myapp-pod
          image: nginx
          
